version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tiptop_db
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: ousama4567/f2i-project-api:release
    ports:
      - "3002:3001"
    depends_on:
      - db

  frontend:
    image: ousama4567/f2i-project-front:release
    ports:
      - "81:80"
    depends_on:
      - api

volumes:
  pgdata:
